### ISSUE TITLE
Validating certs through router.

### ISSUE THREAD

**Issue by cfmagnum** [joutwate/mtls-springboot#1]
Is  there is any way to forward certs through go-router instead of container to container certs validation as go-router has providing feature to forward client certs to app 

Thanks and Regards
Rahul Kumar

**Comment by cybersanjay** [comment]
**ERR_BAD_SSL_CLIENT_AUTH_CERT**
GETTING THE BELOW ON CLIENT CONSOLE:

0610: 0E 00 00 00                                        ....
[Raw read]: length = 5
0000: 16 03 03 00 07                                     .....
[Raw read]: length = 7
0000: 0B 00 00 03 00 00 00                               .......
https-jsse-nio-8222-exec-3, READ: TLSv1.2 Handshake, length = 7
*** Certificate chain
<Empty>
***
https-jsse-nio-8222-exec-3, fatal error: 42: null cert chain
javax.net.ssl.SSLHandshakeException: null cert chain
%% Invalidated:  [Session-12, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
https-jsse-nio-8222-exec-3, SEND TLSv1.2 ALERT:  fatal, description = bad_certificate
https-jsse-nio-8222-exec-3, WRITE: TLSv1.2 Alert, length = 2
https-jsse-nio-8222-exec-3, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLHandshakeException: null cert chain
[Raw write]: length = 7
0000: 15 03 03 00 02 02 2A                               ......*
https-jsse-nio-8222-exec-3, called closeOutbound()
https-jsse-nio-8222-exec-3, closeOutboundInternal()

**Comment by joutwate** [comment]
Sorry, I'm not familiar with go-router. I have since found that using something, such as NGINX, is easier and, in my opinion, a better way to handle certificates rather than have each service handle them directly.
